# -*- coding: utf-8 -*-
"""Zomato.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HV8aR9DEbal79tkI4Pcju-kj_RwPwSJL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns




def handleRate(valueRate):
    rate2=str(valueRate).split("/")
    return float(rate2[0])



dataframe = pd.read_csv(r"/content/sample_data/Zomato_data .csv")
dataframe['rate']=dataframe['rate'].apply(handleRate)
print(dataframe.head())

dataframe.info()

##sns.countplot(x=dataframe['listed_in(type)'])
##plt.xlabel("Type of restaurant")


##grouped_data = dataframe.groupby('listed_in(type)')['votes'].sum()
##result = pd.DataFrame({'votes': grouped_data})
##plt.plot(result, c="green", marker="o")
##plt.xlabel("Type of restaurant", c="red", size=20)
##plt.ylabel("Votes", c="red", size=20)

max_votes=dataframe['votes'].max()
restaurant_with_max_votes = dataframe.loc[dataframe['votes'] == max_votes, 'name']
print("Restaurant(s) with the maximum votes:")
print(restaurant_with_max_votes)


sns.countplot(x=dataframe['online_order'])